// AUTO-GENERATED by scripts/generate-agent-icon-ipfs.ts — do not edit.
import type { AgentIconPresetKey } from "./agent-icons";

export const AGENT_ICON_IPFS_URLS = {
  bot: "ipfs://bafybeidcg4pjdcmxnd7vnpqr2u2f464ggqv5zm6lyewpralvvsec74ppiy",
  activity:
    "ipfs://bafybeiapjebojv5h7vpjiew6twikgsu6boze7gorndwmq3bodvr2e43zti",
  anchor: "ipfs://bafybeihm75qrszgx7qz7wmjb54yzjjifvybbtjsivbncakl7i7dfc6m6ue",
  award: "ipfs://bafybeicsjpf6hlygwogtyki7uvdvevp74q6zbkuvgcufvocju6vqk7alti",
  barChart:
    "ipfs://bafybeib6xoo653i7jie7377lwg7y7zkp53xp3ohjtapkuptrmvf5dcent4",
  beaker: "ipfs://bafybeic65nl6veafhrwa3eyk3spfvg5xls4ymatkx5trfjppvavoqyemsu",
  bell: "ipfs://bafybeifgqlmarfukzsj6xucoy6nmwyjjywppivwwpkpdfqfvfayrxf53ca",
  book: "ipfs://bafybeifebz7v6e2fl3tlr7w45ezzodeuuiklvheiqkklhs3djdtsnrzmde",
  bookmark:
    "ipfs://bafybeifg3ihvihjq2ans2ytmcxvk6ddinpxoxm5xo2mmsdcpao7jbj2ebq",
  box: "ipfs://bafybeie7byybit4xwbifgqbi6vrwee43chngz6arbunni6u3f5dkllbuh4",
  brain: "ipfs://bafybeigsqqk5jonimhoyg7hjq7rhowsvpzp2wacun4idzds6it6r6u5iui",
  briefcase:
    "ipfs://bafybeibuaypyj74ft6z2g3uby7qqsninhtumirymqhnuzx6dugfjyvdemi",
  calendar:
    "ipfs://bafybeic4ecovu5y4p2snefa34cnwpooondaz3qbq3cztd6fckaqvihypxm",
  camera: "ipfs://bafybeiazuqwz6waekafrajtpufk5jhybycxlzktyerx5rctkplqs5k6zlm",
  chartLine:
    "ipfs://bafybeifhsfk7ud6hfzg2qdfiqliobf3q3xoc37i3g3mb3fsa7uemgn6wz4",
  check: "ipfs://bafybeiemzogdy6rwycjlmzb6xqrvuvbjazqzihd3t7qqpi3cgylxpcpplm",
  cloud: "ipfs://bafybeic4y4uksu4dmsvfxytodbfgahnbpfl522ac6kfsvsafwzm67pegti",
  code: "ipfs://bafybeieklhfesskovsepdrbmhm6cjnojhxisu6jsfyjcxbqyl7uiqoc6oi",
  coffee: "ipfs://bafybeif4fh4utv3trftfwjupgl2pdrjv74mgdigzkqjmryshj7ykb23dp4",
  compass: "ipfs://bafybeiamrp27l7rvhijdoobq2nzfubjxmsllf3dhkdb3jqfssmajjltudy",
  cpu: "ipfs://bafybeihdrjyukckklei45donvwdeya4w6fc67fchdwi36huems5tz6u63q",
  crown: "ipfs://bafybeidhy3po45iqqlqe5ziximevbjwjl7fqbbvubeadgkxzdbfjgwz2fe",
  database:
    "ipfs://bafybeiho5r5p7ufw2nruqqgtwldua5hgtkzomfmphhnk2q7f7kgd3isdoy",
  diamond: "ipfs://bafybeig6i3kg4fwq25dbzlldhgqjmabukyphtrdbmmmzjjm2jvuon6xyke",
  feather: "ipfs://bafybeig33kzlbiue4quqzne7yyrjc6hqaxugn2h5bu3oktgcsf4duptgu4",
  fileText:
    "ipfs://bafybeifxoi2zk4uz4etwyzuh3yrlltrxcfgmw7chzououzpcatunzpsray",
  film: "ipfs://bafybeicyo3zif2xrcwxq5chdvqdx74ifqqt75q2wgdf67u7cc7x2j2liw4",
  flame: "ipfs://bafybeidlci3iuktcnyntt26tv45kmzlb623shsqzhq5ptkeridkf5dp32u",
  folder: "ipfs://bafybeiaxmw5h6pougoujaquoepmxlidgl2fkgvkksejnh2jjz4c2urr22m",
  gamepad: "ipfs://bafybeigqyonay5575q3spbunpa24wuero7zuq7jkxcoowfavgpuihtgxz4",
  gift: "ipfs://bafybeig5haa2y2cq6d3kf5hhqegtvtkkg5yskyik7huoadjtb3s2g3ppuy",
  globe: "ipfs://bafybeiciorrpzdokcc2zgeo5ig3ucendsepszmu2fbn527yf5felnelrby",
  graduationCap:
    "ipfs://bafybeicthbjpjhhxpboje26h6g5rksyz5s2ksayxucgo3mxve63645t3w4",
  hammer: "ipfs://bafybeiayt7dg24nd3enlwpktq7ytqotmlrlqtlarqwz2lqc4oodjul2kzm",
  headphones:
    "ipfs://bafybeih6ioyg72buqmwqcpwedwugb5xpvlrezm4fbxospzcu7h5hn4zlle",
  heart: "ipfs://bafybeichsfzuw7usemyiqf6bv5qwqwvwionmm5mwwufkm3ta3z33xbu23i",
  home: "ipfs://bafybeidfg5mmiyqyocliajaxblkxxsblv6y2mx4ieizzzh4khuhqgmujju",
  image: "ipfs://bafybeihr54fkgiyhrpvfwf623rqeejvfg2knqwncydeglerj6hqrvry7ky",
  key: "ipfs://bafybeifqj7rfyuamykypc7dcnrctx5l52mo2djhtcuuabdhzearnh7x5eu",
  layers: "ipfs://bafybeibh4heegea67m2ybnmosm4umwkmfkx3zanuald4y7sxmd3icq7v3q",
  lightbulb:
    "ipfs://bafybeif5vnp7ohlca72zb64dcuikvohdpml4a5zqknj2eya7gxi4i6wrai",
  lock: "ipfs://bafybeiathc2ml53iruakupxhuaoarkgflfhdpceq554yvvc454k5uwztva",
  mail: "ipfs://bafybeidm4jy5lnhyqzgld22po22eosniebvkijg4s6mvdonnzbiwc43zjy",
  map: "ipfs://bafybeigdn47q52n4df27bpypqaqyd4td54omisldwhljtfzy5w4tig5zkm",
  megaphone:
    "ipfs://bafybeia4qmjij6uj57pbau5v4xbyckeunddw6ersdrqsv4ucmswrolzg4m",
  messageSquare:
    "ipfs://bafybeie6vukqdfqrqtcbdgvb46byhmqj6er3owauueykzb5cmfmcpofy5i",
  mic: "ipfs://bafybeie6jgoox22y6z4c7fi2t7n5kiwbxisfxn6x4gmnogeik6v3lnazzy",
  moon: "ipfs://bafybeifo3cvac3f77l4jcs4d3ccnewhaivctj2vyhmif7tdge6rbh4ffuy",
  music: "ipfs://bafybeiaufqvouwnx6dovuewni3dt22trd77gkvgvthaxzixrlxp5rduafq",
  package: "ipfs://bafybeiahv3qlbzfywzwtoqqrzjqxkg2ek66catetitt3bo3eblktlnsy7u",
  palette: "ipfs://bafybeiepqgzkshnm7m6d5wlcd4ei4jxtic6j7gfhsoo3kk3qpvg5sumbhu",
  pen: "ipfs://bafybeicw2zdlpugtsyfppafkj6ngarxxick7q72a62cf763mkoc4fklsu4",
  pencil: "ipfs://bafybeiaxsdpawb4gnqamnlezpmhu5bku2nynpi2hwnc2znpi5drxlztpdi",
  plane: "ipfs://bafybeigjtcbuo7hym6iwc6ife64wsvrzs7wsfzcffy4u6wjgbpzn6kz6bm",
  plug: "ipfs://bafybeigtktgnzusagyhnytg2blrldbndlaolwnrlwho3hxhiaurn7e5rqy",
  puzzle: "ipfs://bafybeibvovcu5voe7q47prvx37avrjenn6h6tadxyebht4oaqqxic5meoi",
  rocket: "ipfs://bafybeiejj7amkzl3qcdcknk4rwcqsrmijjevhvdfse3omyidhzbmnl3ipy",
  scale: "ipfs://bafybeiahzuqcoazrfijvajzvvzjvkrijtyguokfs7fjoiu5c4nc4hazfrm",
  scissors:
    "ipfs://bafybeibp2rujz3qdcyy6ditvoo5e6jkt5ewox4wtvs76jsvxavgsxcsyqe",
  search: "ipfs://bafybeie7gqjej7tvqgzeh3bzg3m3ud5zx7ffpjznfvhdgxo56xn7qeabwy",
  server: "ipfs://bafybeibka3batzjfis4e4l4ptypr6mllw5j7rrmjniytuhlvozhnbq4dta",
  settings:
    "ipfs://bafybeicmonnucibgfiohha6d6a2ex7bfk2ncfhfr4bb5iguvf7nrgsoqua",
  shield: "ipfs://bafybeihrrpy2t7qahpz3lxlsm6tsqeasuj7rvexqxissrr3eplfh2ragji",
  ship: "ipfs://bafybeifngutkwh6u6u47pl2f6jktdfyvna4eavwmju22gypclf2wx2ww34",
  shoppingCart:
    "ipfs://bafybeidkzgwfnmt5726afywvibchbasuuayhdysmkitskitorkh5wyfi2a",
  sparkles:
    "ipfs://bafybeibetra4tgpgxzzjz5w2u3pencytbuucds6hhe7dkhwciwmzgawpjm",
  star: "ipfs://bafybeif3du2n22gwz5c4v2bhbxjgg3bjdkwre7m7kyakzo635ovspue6fi",
  sun: "ipfs://bafybeidf3aqased44eekapn2w66gkwz6pgjvg6jtxopssgw2vyh77lx2ou",
  tag: "ipfs://bafybeid2uerloea5e7vesdthtxzgwlgv3dc45jov2oef2amup7h2e5rrbq",
  target: "ipfs://bafybeifukfdrsc3h7diqzyholwzzt5qyt4uf4txgpno2khnullpaiwgaxm",
  terminal:
    "ipfs://bafybeievsohxgctur6q5upp3z6r3burdj4eempz2bgnzlb6mnr3pveouqm",
  thumbsUp:
    "ipfs://bafybeidrsoeuhkijkdtrq2ro7ji34skjzt4jf2kh6aitpzck4ukq4s4ge4",
  timer: "ipfs://bafybeicndbmqqwilk5rgoovibbbdmvk4qai5mffrdese3thgiogdf42qwy",
  trendingUp:
    "ipfs://bafybeiapoi777txpvjlekzalu22ueoo2g7auxptlq2dkknz5xyybta65xu",
  truck: "ipfs://bafybeiao6u76uicct4772c57r7bv7pgecwovw2vss37epmrjdduudtgtii",
  umbrella:
    "ipfs://bafybeiazfmwxg6oi5is3qzaddvitbdmjomanh4aqbqn344at2x4sbuw6uy",
  user: "ipfs://bafybeiamky7qd3dbrtg35jgjm2icsehqdp3vm57bxjspufggohktzqktmy",
  users: "ipfs://bafybeidz72gkrjlj5vdna7qaqrolqyntfurclnsx6vcmjxlv4qspu7d5pi",
  video: "ipfs://bafybeic2epimm7wuxbtksdshiccm5hxgmz77uw47dxkxnkudtn4y52rc4i",
  wallet: "ipfs://bafybeibfqqcrp2kywkab5zgghk56gydjsemqrkgd2jzhhyl2bnc5amtxgu",
  wrench: "ipfs://bafybeiayarcjtllcgzynsukc4bdnjhfyi4j3g6ycmp7taem7n4qohamzry",
  zap: "ipfs://bafybeifzxd5ugx7agyynbz3aegkmltjwlo73u5jm4deco53wwugj7fhrqq",
} as const satisfies Record<AgentIconPresetKey, string>;

export function resolvePresetAgentIconIpfsUrl(
  preset: AgentIconPresetKey,
): string {
  return AGENT_ICON_IPFS_URLS[preset];
}
