import fs from "node:fs";
import path from "node:path";

const cwd = process.cwd();
const srcRoot = path.join(cwd, "src");
const appRoot = path.join(srcRoot, "app");
const outputPath = path.join(
  srcRoot,
  "lib",
  "openapi",
  "generated",
  "route-app-manifest.ts",
);

function collectRouteFiles(dir: string): string[] {
  const files: string[] = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectRouteFiles(entryPath));
      continue;
    }
    if (entry.isFile() && entry.name === "route.ts") {
      files.push(entryPath);
    }
  }

  return files;
}

/**
 * Route files that do not export a Hono app (or whose handlers we don't want
 * in the aggregated OpenAPI spec). Auth + the spec endpoints themselves stay
 * out of the manifest.
 */
const SKIPPED_PATHS = new Set([
  path.join(appRoot, "api", "auth", "[...all]", "route.ts"),
  path.join(appRoot, "api", "openapi", "route.ts"),
  path.join(appRoot, "api", "v1", "openapi", "route.ts"),
]);

function shouldSkip(routeFile: string): boolean {
  if (SKIPPED_PATHS.has(routeFile)) return true;
  const relative = path.relative(appRoot, routeFile).split(path.sep).join("/");
  // Re-export wrappers under /pay and /registry forward to the canonical
  // /api/* route file via URL aliasing in nextHandlers — no need to register
  // them again.
  if (relative.startsWith("pay/") || relative.startsWith("registry/")) {
    return true;
  }
  // Only routes under /api/* are Hono-based. Other route files (.well-known,
  // magic-link, oidc/consent/submit, jwks) keep their existing Next handlers.
  if (!relative.startsWith("api/")) {
    return true;
  }
  // Skip the spec endpoints themselves so we don't recurse.
  if (
    relative === "api/openapi/route.ts" ||
    relative === "api/v1/openapi/route.ts"
  ) {
    return true;
  }
  return false;
}

function fileUsesHono(file: string): boolean {
  const contents = fs.readFileSync(file, "utf8");
  return (
    /\bcreateApiApp\b/.test(contents) &&
    /\bexport\s+default\s+app\b/.test(contents)
  );
}

const routeFiles = collectRouteFiles(appRoot)
  .filter((file) => !shouldSkip(file))
  .filter((file) => fileUsesHono(file))
  .sort((left, right) => left.localeCompare(right));

const headerLines: string[] = [
  "// This file is generated by src/lib/openapi/generate-route-app-manifest.ts.",
  "// Do not edit by hand — run `pnpm --filter web run openapi:manifest` to update.",
  "// The generated directory is excluded from Prettier and ESLint to keep the",
  "// generator's output authoritative and prevent format-drift churn in CI.",
  "/* eslint-disable */",
];

const importLines: string[] = [
  'import type { OpenAPIHono } from "@hono/zod-openapi";',
];
const entryLines: string[] = [];

function fileExportsRouteMeta(file: string): boolean {
  const contents = fs.readFileSync(file, "utf8");
  return /\bexport\s+const\s+routeMeta\b/.test(contents);
}

routeFiles.forEach((routeFile, index) => {
  const alias = `routeApp${index}`;
  const metaAlias = `routeMeta${index}`;
  const importPath = path
    .relative(path.dirname(outputPath), routeFile)
    .split(path.sep)
    .join("/")
    .replace(/\.ts$/, "");
  const filePath = path.relative(cwd, routeFile).split(path.sep).join("/");
  const hasMeta = fileExportsRouteMeta(routeFile);
  const importLine = hasMeta
    ? `import ${alias}, { routeMeta as ${metaAlias} } from "${importPath.startsWith(".") ? importPath : `./${importPath}`}";`
    : `import ${alias} from "${importPath.startsWith(".") ? importPath : `./${importPath}`}";`;

  importLines.push(importLine);
  entryLines.push(
    `  { app: ${alias} as unknown as OpenAPIHono, meta: ${hasMeta ? metaAlias : "undefined"}, filePath: "${filePath}" },`,
  );
});

const contents = `${headerLines.join("\n")}

${importLines.join("\n")}

export type RouteDocumentKey = "platform" | "public-v1";

export type RouteAppMeta = {
  documents?: readonly RouteDocumentKey[];
};

export type RouteAppManifestEntry = {
  app: OpenAPIHono;
  meta: RouteAppMeta | undefined;
  filePath: string;
};

export const routeAppManifest = [
${entryLines.join("\n")}
] satisfies RouteAppManifestEntry[];
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, contents, "utf8");
console.log(`✓ Route app manifest written to ${outputPath}`);
